name: CI-CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Application Build
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Instalar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Construir app Java
      run: mvn clean package

    - name: Guardar archivo .jar
      uses: actions/upload-artifact@v3
      with:
        name: app-jar
        path: target/*.jar

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Descargar archivo .jar
      uses: actions/download-artifact@v3
      with:
        name: app-jar
        path: target

    - name: Iniciar sesión en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Crear imagen Docker
      run: docker build -t duvangt/julio-salazar:v1.0 .

    - name: Subir imagen a DockerHub
      run: docker push duvangt/julio-salazar:v1.0
